### ISSUE TITLE
ConformityCredential Product vs DPP Product

### ISSUE THREAD

**Issue by Fak3** [uncefact/spec-untp#110]
On the [ConformityCredential diagram](https://github.com/uncefact/spec-untp/blob/main/website/docs/specification/ConformityCredential.svg) There is a _Product_ class, which has properties `testedBatchId` and `verifiedByCAB` which do not belong to the generic Product, but to the particular _ConformityAsessment_
![Screenshot_20240613_131738](https://github.com/uncefact/spec-untp/assets/991641/d0444212-f56c-40f4-8179-721a377dc270)
If there are multiple  _ConformityAsessment_ of the same product, the resulting graph will appear confusing, as json object nesting is lost at the graph level:
```yaml
- type: ConformityAsessment
  subjectProducts:
  - id: product1
    testedBatchId: goodBatch1
- type: ConformityAsessment
  subjectProducts:
  - id: product1
    testedBatchId: badBatch1
```
will result in RDF graph triples:
```turtle
product1 testedBatchId goodBatch1;
product1 testedBatchId badBatch1;
```
The association of product batch to the measured results is lost.

One potential way to correctly model the graph is to introduce _ProductAsessment_ class:

```mermaid
classDiagram
    ConformityAsessment <|-- ProductAsessment
    ProductAsessment <|-- Product
    class ConformityAsessment{
      ProductAsessment subjectProducts
    }
    class ProductAsessment{
      URI testedBatchId
      Product product
    }
    class Product{
      Identifier indentifier
      Text modelName
    }
```

Another way could be to rename Product to the ProductAsessment, so that the assessment has unique id, distinct form the Product id
